name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

# Only allow one build per branch at a time. New builds will NOT cancel existing builds.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish tagged packages
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          fetch-tags: 0
      - uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        with:
          packages: git gpg leiningen
          # Increment this when the package list changes.
          version: 1
      - name: Cache ~/.m2
        uses: actions/cache@v4
        with:
          path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-m2-
      - name: Configure GPG Key
        run: |
          echo -n "${JANK_GPG_SIGNING_KEY}" | gpg --import
        env:
          JANK_GPG_SIGNING_KEY: ${{ secrets.JANK_GPG_SIGNING_KEY }}
      - name: Configure Leiningen
        run: |
          mkdir -p ~/.lein
          echo '{:user {:repositories [["clojars" {:url "https://clojars.org/repo" :username :env/lein_username :password :env/lein_password}]]}}' > ~/.lein/profiles.clj
      - name: Find and publish
        run: ${{ github.workspace }}/bin/publish ${{ github.event.before }} ${{ github.sha }} || exit 1
        env:
          LEIN_USERNAME: ${{ secrets.LEIN_USERNAME }}
          LEIN_PASSWORD: ${{ secrets.LEIN_PASSWORD }}
